name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;30.0.14904198"

      - name: Set env
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/30.0.14904198" >> $GITHUB_ENV

      - name: Make scripts executable
        run: |
          chmod +x ./gradlew
          chmod +x buildScript/libwg-go/build-libwg-go.sh
          chmod +x buildScript/lib/core/init.sh
          chmod +x buildScript/lib/core/get_source.sh
          chmod +x buildScript/lib/core/build.sh

      - name: Prepare libcore sources
        run: bash buildScript/lib/core/init.sh

      - name: Install gomobile-matsuri
        working-directory: libcore/gomobile
        run: |
          go version
          go install ./cmd/gomobile-matsuri
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build libcore
        run: bash buildScript/lib/core/build.sh

      - name: Build libwg-go
        run: ./gradlew :app:buildLibWgGo --no-daemon --stacktrace

      - name: Build APK
        run: ./gradlew assembleArm64FdroidRelease --no-daemon --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            app/build/outputs/apk/**/*.apk
            app/executableSo/**/libwg-go.so
