name: Android CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build libwg-go
        run: ./gradlew :app:buildLibWgGo --no-daemon --stacktrace

      - name: Build APK
        run: ./gradlew assembleArm64FdroidRelease --no-daemon --stacktrace
